# .github/workflows/refresh-models.yml
name: Refresh Models Registry (Daily)

on:
  schedule:
    - cron: "17 2 * * *"   # يوميًا 02:17 UTC (05:17 بتوقيت بغداد +03:00)
  workflow_dispatch:       # تشغيل يدوي للتجربة

permissions:
  contents: write          # مهم لعمل push بتوكن GitHub الافتراضي

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Build models.json
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python build_models_json.py

      - name: Show diff
        run: |
          git status
          git diff -- models.json || true

      - name: Commit & push if changed
        run: |
          set -e
          if ! git diff --quiet --exit-code -- models.json; then
            git config user.name  "actions-bot"
            git config user.email "actions-bot@users.noreply.github.com"
            git add models.json
            git commit -m "chore(models): daily refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes in models.json; skipping commit."
          fi
